# Use postgres/example user/password credentials
version: '3.8'

services:
  web:
    image: nginx
    networks:
      - internal
    volumes:
      - ./nginx/templates:/etc/nginx/templates
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_PORT=80
    depends_on:
      - identifier

  db:
    image: postgres
    restart: always
    networks:
      - internal
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: asdhjkhg85ygfvd14e7bjh
      POSTGRES_DB: app

  adminer:
    image: adminer
    restart: always
    networks:
      - internal
    ports:
      - 49152:8080

  identifier:
    build:
      context: identifier/.
      dockerfile: Dockerfile
    networks:
      - internal
    volumes:
      - ./identifier/:/usr/src/app/
    ports:
      - 8080:8080
    depends_on:
      - db

networks:
  internal:
    driver: bridge